import { GoogleGenerativeAI } from "@google/generative-ai";

// 1. Configuration
const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

if (!apiKey) {
  throw new Error("VITE_GEMINI_API_KEY is missing. Set it in your .env file.");
}

// ✅ Initialize the SDK (Much safer than manual fetch)
const genAI = new GoogleGenerativeAI(apiKey);

// ✅ Use the correct model name: "gemini-1.5-flash"
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

// 2. Types
export interface GenerateContentParams {
  prompt: string;
  contentType: "blog" | "script" | "song" | "essay";
  tone: "professional" | "casual" | "inspirational" | "humorous";
  length: "short" | "medium" | "long";
}

const lengthGuidelines = {
  short: "around 300 words",
  medium: "around 600 words",
  long: "around 1000 words",
} as const;

const contentTypeInstructions = {
  blog: "Write a well-structured blog post with an engaging introduction, informative body paragraphs, and a compelling conclusion.",
  script: "Write a script format with scene descriptions, character dialogue, and stage directions.",
  song: "Write song lyrics with verses, chorus, and bridge. Include emotion and rhythm.",
  essay: "Write a formal essay with a clear thesis, supporting arguments, and evidence.",
} as const;

// 3. Main function
export async function generateContent({
  prompt,
  contentType,
  tone,
  length,
}: GenerateContentParams): Promise<string> {
  const finalPrompt = `You are an expert ${contentType} writer. 
  
Topic: ${prompt}

Instructions:
- ${contentTypeInstructions[contentType]}
- Tone: ${tone}
- Length: ${lengthGuidelines[length]}
- Make it engaging, well-structured, and high-quality.
- Use proper formatting with paragraphs.

Write the ${contentType} now:
`;

  try {
    // ✅ Use the SDK method instead of fetch
    const result = await model.generateContent(finalPrompt);
    const response = await result.response;
    const text = response.text();

    if (!text) {
      throw new Error("No content generated by Gemini.");
    }

    return text;
  } catch (error) {
    console.error("Gemini API Error:", error);
    // If the error is still a 404 here, it means the API key is invalid or the model is down
    throw new Error("Failed to generate content. Please try again.");
  }
}